spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EcomGlobe?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Vinayak@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
